# Site settings
title: Charity Leaks
url: https://charity-leaks.github.io
description: "Do you like good detective stories? Ever heard of Citizen Kane? Spotlight? All these movies with the heroic journalists? If so, come aboard, forget fiction but keep the popcorn, and dive into the world of the rogue offshore financial industry, where leaders, criminals, celebrities and yes, charities, rub shoulders."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: WangCorp

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
